version: 2.1

executors:
  azure-executor:
    docker:
      - image: mcr.microsoft.com/azure-cli:latest
    working_directory: ~/project

orbs:
  azure-cli: circleci/azure-cli@1.3.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package

  deploy:
    executor: azure-executor
    steps:
      - checkout
      - run:
          name: Update and Install GPG
          command: |
            apt-get update && apt-get install -y gnupg
      - run:
          name: Add Missing GPG Key for Debian Repositories
          command: |
            gpg --keyserver keyserver.ubuntu.com --recv-keys 32EE5355A6BC6E42
            gpg --export --armor 32EE5355A6BC6E42 | apt-key add -
      - azure-cli/install
      - run:
          name: Log in to Azure with Service Principal
          command: |
            az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path target/*.jar
            echo "Deployment successful"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

contexts:
  azure-context:
    environment:
      AZURE_SP: your_sp_id
      AZURE_SP_PASSWORD: your_sp_password
      AZURE_SP_TENANT: your_sp_tenant
