version: 2.1

orbs:
  azure-cli: circleci/azure-cli@0.1.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Azure CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - azure-cli/install
      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Deploy to Azure App Service (Windows)
          command: |
            # Replace <resource-group-name> and <app-service-name> with your actual resource group and app service names
            az webapp deploy --resource-group eshwar --name middleware-talents --src-path target/ems-backend-0.0.1-SNAPSHOT.jar
            az webapp ssh --resource-group eshwar --name middleware-talents --command "java -jar target/ems-backend-0.0.1-SNAPSHOT.jar"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

