version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package

  deploy:
    steps:
      - checkout
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group <resource-group-name> --name <app-service-name> --src-path target/<your-app>.war

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
