version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Dependencies and Google Chrome Public Key
          command: |
            sudo apt-get update && sudo apt-get install -y curl wget gnupg
            curl -sSL https://dl.google.com/linux/linux_signing_key.pub | sudo tee /etc/apt/trusted.gpg.d/google.asc
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
      - run:
          name: Update System Packages
          command: |
            sudo apt-get update
            sudo apt-get upgrade -y
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - run:
          name: Export Azure Environment Variables
          command: |
            # Replace these values with your actual Azure credentials
            export CLIENT_ID="f1db75c3-09cc-474c-a124-052bcb6cfc06"
         
            export TENANT_ID="118b2919-e434-405b-9f3c-3a829eba55f9"

      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $TENANT_ID --debug

      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path target/*.jar
            echo "Deployment successful"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
