version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy  # Use OpenJDK 17 for building the Java app
    steps:
      - checkout  # Checkout the code from GitHub
      - run:
          name: Resolve GPG Key Issue for Google Chrome Repository
          command: |
            sudo apt-get update
            sudo apt-get install -y wget
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google.gpg
            echo "deb [signed-by=/usr/share/keyrings/google.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
      - run:
          name: Build with Maven
          command: mvn clean package  # This will build and package your app into a .jar file

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy  # Reuse OpenJDK 17 image for deployment consistency
    steps:
      - checkout  # Checkout the repo again
      - run:
          name: Install Azure CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash  # Install Azure CLI
      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID  # Log into Azure using the Service Principal credentials
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group ed --name middleware-talents --src-path target/*.jar  # Deploy the .jar file to Azure App Service

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build  # Ensure deploy runs after build job completes successfully
          filters:
            branches:
              only:
                - main  # Trigger the workflow only for the 'main' branch