version: 2.1
executors:
  azure-executor:
    docker:
      - image: mcr.microsoft.com/azure-cli:latest
    working_directory: ~/project
jobs:
  azure-login:
    executor: azure-executor
    steps:
      - checkout
      - run:
          name: Login with Azure CLI
          command: |
            az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
workflows:
  version: 2
  login_and_execute:
    jobs:
      - azure-login
contexts:
  azure-context:
    environment:
      AZURE_SP: your_sp_id
      AZURE_SP_PASSWORD: your_sp_password
      AZURE_SP_TENANT: your_sp_tenant