version: 2.1

orbs:
  azure: circleci/azure-cli@1.3.2  # Use the Azure CLI Orb for simplified Azure commands

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy  # Use an OpenJDK-based image for building the JAR
    steps:
      - checkout
      - run:
          name: Build Java backend with Maven
          command: mvn clean package  # This will create the JAR file in target/
      - persist_to_workspace:
          root: ./target  # Save the JAR file for deployment
          paths:
            - .

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy  # Use the same image as the build job
    steps:
      - attach_workspace:
          at: /workspace  # Attach the workspace to retrieve the JAR file
      - azure/login:
          client-id: $AZURE_CLIENT_ID
          client-secret: $AZURE_CLIENT_SECRET
          tenant-id: $AZURE_TENANT_ID
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar \
                              --name middleware-talents \
                              --src-path /workspace/ems-backend-0.0.1-SNAPSHOT.jar \
                              --type jar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
