version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install missing GPG key for Google Chrome
          command: |
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-archive-keyring.gpg
      - run:
          name: Fix Google Chrome repository
          command: |
            echo "deb [signed-by=/usr/share/keyrings/google-archive-keyring.gpg] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
      - run:
          name: Update and install Chrome
          command: |
            sudo sed -i 's/oldstable/oldoldstable/g' /etc/apt/sources.list
            sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run:
          name: Build with Maven
          command: mvn clean package

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name middle-ware --src-path target/ems-backend-0.0.1-SNAPSHOT.jar

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
