version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.3.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Add Missing GPG Key for Debian Repositories
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 32EE5355A6BC6E42
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path target/*.jar
            echo "Deployment successful"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
