version: 2.1

executors:
  azure-executor:
    docker:
      - image: ubuntu:20.04  # Use an Ubuntu image with apt-get
    working_directory: ~/project

orbs:
  azure-cli: circleci/azure-cli@1.3.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: List files in target directory
          command: ls -l /home/circleci/project/target
      - store_artifacts:
          path: target/ems-backend-0.0.1-SNAPSHOT.jar
          destination: ems-backend-0.0.1-SNAPSHOT.jar    

  deploy:
    executor: azure-executor
    steps:
      - checkout
      - run:
          name: Install curl and gnupg
          command: |
            apt-get update && apt-get install -y gnupg2 curl lsb-release
      - run:
          name: Add Missing GPG Key for Debian Repositories
          command: |
            curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | tee /etc/apt/trusted.gpg.d/google.asc
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google-chrome.list
            apt-get update
      - azure-cli/install
      - run:
          name: Log in to Azure with Service Principal
          command: |
            az login --service-principal -u $AZURE_SP -p $AZURE_SP_PASSWORD --tenant $AZURE_SP_TENANT
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name eshwar-backend --src-path ems-backend-0.0.1-SNAPSHOT.jar --type zip
            echo "Deployment successful"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

contexts:
  azure-context:
    environment:
      AZURE_SP: your_sp_id
      AZURE_SP_PASSWORD: your_sp_password
      AZURE_SP_TENANT: your_sp_tenant
