version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean package
      - persist_to_workspace:
          root: .
          paths:
            - target/*.jar

  deploy:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Azure CLI
          command: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      - run:
          name: Log in to Azure
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      - run:
          name: Deploy to Azure App Service
          command: |
            az webapp deploy --resource-group eshwar --name middleware-talents--src-path target/ems-backend-0.0.1-SNAPSHOT.jar  --type jar

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main